=== amoore877/personal_fun/trunk/Recreation/src/games/rolePlayingGames/shadowrun/tracking/trackables/xml/xsd/ShadowrunSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="agent" type="agent"/>

  <xs:element name="armorEquipment" type="armorEquipment"/>

  <xs:element name="character" type="character"/>

  <xs:element name="chargedMeleeWeapon" type="chargedMeleeWeapon"/>

  <xs:element name="device" type="device"/>

  <xs:element name="firearm" type="firearm"/>

  <xs:element name="hacker" type="hacker"/>

  <xs:element name="item" type="item"/>

  <xs:element name="meleeWeapon" type="meleeWeapon"/>

  <xs:element name="pilotDevice" type="pilotDevice"/>

  <xs:element name="projectileWeapon" type="projectileWeapon"/>

  <xs:element name="quality" type="quality"/>

  <xs:element name="skill" type="skill"/>

  <xs:element name="spell" type="spell"/>

  <xs:element name="spirit" type="spirit"/>

  <xs:element name="statusEffect" type="statusEffect"/>

  <xs:element name="technomancer" type="technomancer"/>

  <xs:element name="timedItem" type="timedItem"/>

  <xs:complexType name="pilotDevice">
    <xs:complexContent>
      <xs:extension base="matrixBeing">
        <xs:sequence>
          <xs:element name="armor" type="xs:int"/>
          <xs:element name="body" type="xs:int"/>
          <xs:element name="inventory" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="inventory" type="equipment" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="pilot" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="matrixBeing" abstract="true">
    <xs:sequence>
      <xs:element name="abilities" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="abilities" type="ability" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="dataProcessing" type="xs:int"/>
      <xs:element name="firewall" type="xs:int"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="rating" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="equipment" abstract="true">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="armorEquipment">
    <xs:complexContent>
      <xs:extension base="equipment">
        <xs:sequence>
          <xs:element name="armor" type="xs:int"/>
          <xs:element name="benefits" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="item">
    <xs:complexContent>
      <xs:extension base="equipment">
        <xs:sequence>
          <xs:element name="armor" type="xs:int"/>
          <xs:element name="body" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="timedItem">
    <xs:complexContent>
      <xs:extension base="item">
        <xs:sequence>
          <xs:element name="effect" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="device">
    <xs:complexContent>
      <xs:extension base="item">
        <xs:sequence>
          <xs:element name="rating" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="weapon" abstract="true">
    <xs:complexContent>
      <xs:extension base="equipment">
        <xs:sequence>
          <xs:element name="accuracy" type="xs:int"/>
          <xs:element name="armorPiercing" type="xs:int"/>
          <xs:element name="benefits" type="xs:string"/>
          <xs:element name="damageElement" type="damageElement"/>
          <xs:element name="damageValue" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="meleeWeapon">
    <xs:complexContent>
      <xs:extension base="weapon">
        <xs:sequence>
          <xs:element name="reach" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="chargedMeleeWeapon">
    <xs:complexContent>
      <xs:extension base="meleeWeapon">
        <xs:sequence>
          <xs:element name="clipCapacity" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="rangedWeapon" abstract="true">
    <xs:complexContent>
      <xs:extension base="weapon">
        <xs:sequence>
          <xs:element name="rangedWeaponType" type="rangedWeaponType"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="projectileWeapon">
    <xs:complexContent>
      <xs:extension base="rangedWeapon">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="firearm">
    <xs:complexContent>
      <xs:extension base="rangedWeapon">
        <xs:sequence>
          <xs:element name="firingModes" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="firingModes" type="firingMode" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="recoilCompensation" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ability" abstract="true">
    <xs:sequence>
      <xs:element name="fullDesc" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="skill">
    <xs:complexContent>
      <xs:extension base="ability">
        <xs:sequence>
          <xs:element name="level" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="spell">
    <xs:complexContent>
      <xs:extension base="ability">
        <xs:sequence>
          <xs:element name="briefDesc" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="agent">
    <xs:complexContent>
      <xs:extension base="matrixBeing">
        <xs:sequence>
          <xs:element name="attack" type="xs:int"/>
          <xs:element name="sleaze" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="technomancer">
    <xs:complexContent>
      <xs:extension base="character">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="character">
    <xs:complexContent>
      <xs:extension base="livingBeing">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="livingBeing" abstract="true">
    <xs:sequence>
      <xs:element name="abilities" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="abilities" type="ability" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="agility" type="xs:int"/>
      <xs:element name="body" type="xs:int"/>
      <xs:element name="charisma" type="xs:int"/>
      <xs:element name="essence" type="xs:int"/>
      <xs:element name="initDice" type="xs:int"/>
      <xs:element name="intuition" type="xs:int"/>
      <xs:element name="inventory" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="inventory" type="equipment" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="logic" type="xs:int"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="qualities" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="qualities" type="quality" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="reaction" type="xs:int"/>
      <xs:element name="special" type="xs:int"/>
      <xs:element name="statusEffects" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="statusEffects" type="statusEffect" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="strength" type="xs:int"/>
      <xs:element name="willpower" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="quality">
    <xs:sequence>
      <xs:element name="briefDesc" type="xs:string"/>
      <xs:element name="combatQuality" type="xs:boolean"/>
      <xs:element name="fullDesc" type="xs:string"/>
      <xs:element name="qualityType" type="qualityType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="statusEffect">
    <xs:sequence>
      <xs:element name="briefDesc" type="xs:string"/>
      <xs:element name="combatStatusEffect" type="xs:boolean"/>
      <xs:element name="fullDesc" type="xs:string"/>
      <xs:element name="statusEffectType" type="statusEffectType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="spirit">
    <xs:complexContent>
      <xs:extension base="livingBeing">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="hacker">
    <xs:complexContent>
      <xs:extension base="character">
        <xs:sequence>
          <xs:element name="attack" type="xs:int"/>
          <xs:element name="dataProcessing" type="xs:int"/>
          <xs:element name="firewall" type="xs:int"/>
          <xs:element name="rating" type="xs:int"/>
          <xs:element name="sleaze" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="damageElement">
    <xs:restriction base="xs:string">
      <xs:enumeration value="REGULAR"/>
      <xs:enumeration value="ACID"/>
      <xs:enumeration value="COLD"/>
      <xs:enumeration value="ELECTRIC"/>
      <xs:enumeration value="FIRE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="rangedWeaponType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TASER"/>
      <xs:enumeration value="HOLDOUT"/>
      <xs:enumeration value="LGT_PISTOL"/>
      <xs:enumeration value="HVY_PISTOL"/>
      <xs:enumeration value="MP"/>
      <xs:enumeration value="SMG"/>
      <xs:enumeration value="AR"/>
      <xs:enumeration value="FLECHETTE_SHOTGUN"/>
      <xs:enumeration value="SLUG_SHOTGUN"/>
      <xs:enumeration value="SNIPER"/>
      <xs:enumeration value="LMG"/>
      <xs:enumeration value="HMG"/>
      <xs:enumeration value="CANNON"/>
      <xs:enumeration value="GL"/>
      <xs:enumeration value="MISSILE"/>
      <xs:enumeration value="BOW"/>
      <xs:enumeration value="LGT_CROSSBOW"/>
      <xs:enumeration value="MED_CROSSBOW"/>
      <xs:enumeration value="HVY_CROSSBOW"/>
      <xs:enumeration value="THROWING_KNIFE"/>
      <xs:enumeration value="SHURIKEN"/>
      <xs:enumeration value="STD_GRENADE"/>
      <xs:enumeration value="AERO_GRENADE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="firingMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SS"/>
      <xs:enumeration value="SA"/>
      <xs:enumeration value="BF"/>
      <xs:enumeration value="FA"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="qualityType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="POSITIVE"/>
      <xs:enumeration value="NEGATIVE"/>
      <xs:enumeration value="NEUTRAL"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="statusEffectType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="POSITIVE"/>
      <xs:enumeration value="NEGATIVE"/>
      <xs:enumeration value="NEUTRAL"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== amoore877/personal_fun/trunk/Recreation/resources/tracking/meleeweapon/Combat_Axe.xml
<?xml version="1.0" encoding="UTF-8"?>
<meleeWeapon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../src/games/rolePlayingGames/shadowrun/tracking/trackables/xml/xsd/ShadowrunSchema.xsd" xsi:type="meleeWeapon">
  <name>Combat Axe</name>
  <id>51711c87-6bce-424c-820e-b2fa76df74cf</id>
  <accuracy>4</accuracy>
  <damageValue>5</damageValue>
  <armorPiercing>-4</armorPiercing>
  <damageElement>REGULAR</damageElement>
  <benefits>none</benefits>
  <reach>2</reach>
</meleeWeapon>

=== amoore877/personal_fun/ShadowrunTracking/resources/tracking/shadowrun/meleeweapon/Katana.xml
<?xml version="1.0" encoding="UTF-8"?>
<meleeWeapon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../src/games/rolePlayingGames/shadowrun/tracking/trackables/xml/xsd/ShadowrunSchema.xsd" xsi:type="meleeWeapon">
  <name>Katana</name>
  <id>3a3a2444-9b82-473f-91d1-a1a0b87cad28</id>
  <accuracy>7</accuracy>
  <damageValue>3</damageValue>
  <armorPiercing>-3</armorPiercing>
  <damageElement>REGULAR</damageElement>
  <benefits>none</benefits>
  <reach>1</reach>
</meleeWeapon>

=== amoore877/personal_fun/trunk/RPGTracking/resources/tracking/shadowrun/character/Elite_Ganger.xml
<?xml version="1.0" encoding="UTF-8"?>
<character xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../src/games/rolePlayingGames/shadowrun/tracking/trackables/xml/xsd/ShadowrunSchema.xsd">
	<name>Elite Ganger</name>
	<special>0</special>
	<statusEffects>
	</statusEffects>
	<inventory>
		<!-- Knife -->
		<inventoryID>60873b15-34e4-446f-984c-aff16d1c1b09</inventoryID>
		<!-- Rating 2 Commlink -->
		<inventoryID>b3a2b6e5-c5e7-49c7-a006-fe0a77f66d7f</inventoryID>
		<!-- Browning Ultra-Power -->
		<inventoryID>4161e7df-b49f-42b2-8290-cd2e78653dc6</inventoryID>
		<!-- Armor Jacket -->
		<inventoryID>be398a63-797a-47ef-ad93-5d3e05b423bb</inventoryID>
	</inventory>
	<qualities>
		<!-- Toughness -->
		<qualityID>abb5ddc4-12d1-4b5b-a284-e70a1bd61806</qualityID>
	</qualities>
	<body>4</body>
	<willpower>4</willpower>
	<agility>4</agility>
	<reaction>4</reaction>
	<strength>4</strength>
	<logic>3</logic>
	<intuition>4</intuition>
	<charisma>4</charisma>
	<initDice>2</initDice>
	<skills>
		<skill>
			<fullDesc>Blades</fullDesc>
			<level>5</level>
		</skill>
		<skill>
			<fullDesc>Leadership</fullDesc>
			<level>1</level>
		</skill>
		<skill>
			<fullDesc>Intimidation</fullDesc>
			<level>4</level>
		</skill>
		<skill>
			<fullDesc>Pistols</fullDesc>
			<level>5</level>
		</skill>
		<skill>
			<fullDesc>Unarmed Combat</fullDesc>
			<level>5</level>
		</skill>
		<skill>
			<fullDesc>Thrown Weapons</fullDesc>
			<level>2</level>
		</skill>
	</skills>
	<spells>
	</spells>
	<essence>5</essence>
</character>

=== amoore877/personal_fun/ShadowrunTracking/resources/tracking/shadowrun/meleeweapon/Monofilament_Whip.xml
<?xml version="1.0" encoding="UTF-8"?>
<meleeWeapon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../src/games/rolePlayingGames/shadowrun/tracking/trackables/xml/xsd/ShadowrunSchema.xsd" xsi:type="meleeWeapon">
  <name>Monofilament Whip</name>
  <id>177f1408-b5ee-45d7-92a6-f5bc31d1346d</id>
  <accuracy>7</accuracy>
  <damageValue>12</damageValue>
  <armorPiercing>-8</armorPiercing>
  <damageElement>REGULAR</damageElement>
  <benefits>none</benefits>
  <reach>2</reach>
</meleeWeapon>

=== amoore877/personal_fun/Recreation/resources/tracking/character/Police_Patrol.xml
<?xml version="1.0" encoding="UTF-8"?>
<character xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../src/games/rolePlayingGames/shadowrun/tracking/trackables/xml/xsd/ShadowrunSchema.xsd">
	<name>Police Patrol</name>
	<special>0</special>
	<statusEffects>
	</statusEffects>
	<inventory>
		<!-- Rating 3 Commlink -->
		<inventoryID>b874c9af-9734-462f-8746-676b3869d666</inventoryID>
		<!-- Ares Predator V -->
		<inventoryID>0d52c869-658d-4211-8b0b-5d3fb21a4222</inventoryID>
		<!-- Defiance EX Shocket -->
		<inventoryID>4f36a452-7db2-41b7-93e6-4f7f37282252</inventoryID>
		<!-- Stun Baton -->
		<inventoryID>7f23a4e3-5d1f-4d9f-8b65-e11252672ee2</inventoryID>
		<!-- Armor Jacket -->
		<inventoryID>be398a63-797a-47ef-ad93-5d3e05b423bb</inventoryID>
	</inventory>
	<qualities>
	</qualities>
	<body>4</body>
	<willpower>3</willpower>
	<agility>3</agility>
	<reaction>4</reaction>
	<strength>3</strength>
	<logic>2</logic>
	<intuition>3</intuition>
	<charisma>3</charisma>
	<initDice>3</initDice>
	<skills>
		<skill>
			<fullDesc>Running</fullDesc>
			<level>3</level>
		</skill>
		<skill>
			<fullDesc>Perception</fullDesc>
			<level>3</level>
		</skill>
		<skill>
			<fullDesc>Pistols</fullDesc>
			<level>4</level>
		</skill>
		<skill>
			<fullDesc>Clubs</fullDesc>
			<level>3</level>
		</skill>
		<skill>
			<fullDesc>Unarmed Combat</fullDesc>
			<level>4</level>
		</skill>
	</skills>
	<spells>
	</spells>
	<essence>6</essence>
</character>

=== amoore877/personal_fun/trunk/Recreation/resources/tracking/meleeweapon/Pole_Arm.xml
<?xml version="1.0" encoding="UTF-8"?>
<meleeWeapon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../src/games/rolePlayingGames/shadowrun/tracking/trackables/xml/xsd/ShadowrunSchema.xsd" xsi:type="meleeWeapon">
  <name>Pole Arm</name>
  <id>9ef1baaf-76ba-4464-9d8d-5a62e0460ce9</id>
  <accuracy>5</accuracy>
  <damageValue>3</damageValue>
  <armorPiercing>-2</armorPiercing>
  <damageElement>REGULAR</damageElement>
  <benefits>none</benefits>
  <reach>3</reach>
</meleeWeapon>

=== amoore877/personal_fun/ShadowrunTracking/resources/tracking/shadowrun/meleeweapon/Combat_Knife.xml
<?xml version="1.0" encoding="UTF-8"?>
<meleeWeapon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../src/games/rolePlayingGames/shadowrun/tracking/trackables/xml/xsd/ShadowrunSchema.xsd" xsi:type="meleeWeapon">
  <name>Combat Knife</name>
  <id>ebc85001-5272-43a0-9717-f35a99d36204</id>
  <accuracy>6</accuracy>
  <damageValue>2</damageValue>
  <armorPiercing>-3</armorPiercing>
  <damageElement>REGULAR</damageElement>
  <benefits>none</benefits>
  <reach>0</reach>
</meleeWeapon>

=== amoore877/personal_fun/Recreation/resources/tracking/meleeweapon/Extendable_Baton.xml
<?xml version="1.0" encoding="UTF-8"?>
<meleeWeapon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../src/games/rolePlayingGames/shadowrun/tracking/trackables/xml/xsd/ShadowrunSchema.xsd" xsi:type="meleeWeapon">
  <name>Extendable Baton</name>
  <id>4d4728e7-5516-475c-af3e-21267e539be0</id>
  <accuracy>5</accuracy>
  <damageValue>2</damageValue>
  <armorPiercing>0</armorPiercing>
  <damageElement>REGULAR</damageElement>
  <benefits>none</benefits>
  <reach>1</reach>
</meleeWeapon>
